server:
  port: 8002
  mode: "dev"
mysql: 
  host: 127.0.0.1
  port: 3307
  username: root
  password: root1234
  dbname: shopdevgo
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
logger:
  log_level: debug
  file_log_name: ./storages/logs/dev.001.log
  max_size:    500
  max_backups: 3
  max_age:     28
  compress:   true
redis:
  host: 127.0.0.1
  port: 6381
  password: # no pw set
  db: 0 # use default db
  pool_size: 10 # max connect to redis